import { NextPage } from "next";
import React, { ReactNode } from "react";
import Head from 'next/head'

interface layoutProps{children:ReactNode}

const Layout:NextPage<layoutProps> = ({children}) => {
  return(
    <main 
     className="min-h-screen min-w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </main>
  )
}


export default Layout
